### ISSUE TITLE
关于单例模式的不解

### ISSUE THREAD

**Issue by immarktube** [qiaoyunrui/StudyNote#1]
您好，
    在设计模式 -> 单例模式 -> Double Check Lock(DCL)实现单例 的两个if(singletan3 == null)
    这里我看了您的解释还是有些不解，既然第一次判断空了然后还上锁了为什么还要再去判断一次呢？
    请前辈答疑解惑！拜谢！

**Comment by immarktube** [comment]
您且看我解释的对不对，外面的判断是个假判断，不加同步锁，里面的判断才是真判断，这样写是要确保唯一，避免高并发情况下创建多个对象。

**Comment by qiaoyunrui** [comment]
是的，你说的很对。
